; Script generated by the Inno Script Studio Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

#define MyAppName "IPTS"
#define MyAppVersion "1.5.2"
#define MyAppPublisher "Fondazione Istituto Italiano di Tecnologia"
#define MyAppURL "http://www.iit.it/"
#define MyAppExeName "iCubProductionTestSuite.exe"

[Setup]
; NOTE: The value of AppId uniquely identifies this application.
; Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{41684992-700A-4A72-A6B2-25DF7939F22B}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
;AppVerName={#MyAppName} {#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
DefaultDirName={sd}\Istituto Italiano di Tecnologia\{#MyAppName}
DefaultGroupName={#MyAppName}
OutputBaseFilename=IPTS-Setup
Compression=lzma
SolidCompression=yes

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"

[Icons]
Name: "{group}\{#MyAppName}"; Filename: "{app}\bin\Release\{#MyAppExeName}"; IconFilename: "{app}\img\icub.ico"
Name: "{commondesktop}\{#MyAppName}"; Filename: "{app}\bin\Release\{#MyAppExeName}"; IconFilename: "{app}\img\icub.ico"; Tasks: desktopicon



[Run]
Filename: "{app}\tools\STM32 ST-LINK Utility v4.5.0.exe"
Filename: "{app}\tools\Git-2.31.1-64-bit.exe"

[Files]
Source: "iCubProductionTestSuite\tools\STM32 ST-LINK Utility v4.5.0.exe"; DestDir: "{app}\tools"; Flags: ignoreversion
Source: "iCubProductionTestSuite\tools\drivers_can\Win32\C200\canc200.cat"; DestDir: "{app}\tools\drivers_can\Win32\C200"; Flags: ignoreversion
Source: "iCubProductionTestSuite\tools\drivers_can\Win32\C200\canc200.inf"; DestDir: "{app}\tools\drivers_can\Win32\C200"; Flags: ignoreversion
Source: "iCubProductionTestSuite\tools\drivers_can\Win32\C200\relnotes.html"; DestDir: "{app}\tools\drivers_can\Win32\C200"; Flags: ignoreversion
Source: "iCubProductionTestSuite\tools\drivers_can\Win32\C200\x86\c200.sys"; DestDir: "{app}\tools\drivers_can\Win32\C200\x86"; Flags: ignoreversion
Source: "iCubProductionTestSuite\tools\drivers_can\Win32\C200\x86\calcan32.dll"; DestDir: "{app}\tools\drivers_can\Win32\C200\x86"; Flags: ignoreversion
Source: "iCubProductionTestSuite\tools\drivers_can\Win32\C200\x86\canui32.dll"; DestDir: "{app}\tools\drivers_can\Win32\C200\x86"; Flags: ignoreversion
Source: "iCubProductionTestSuite\tools\drivers_can\Win32\C200\x86\ntcan.dll"; DestDir: "{app}\tools\drivers_can\Win32\C200\x86"; Flags: ignoreversion
Source: "iCubProductionTestSuite\tools\drivers_can\Win32\C331\canc331.cat"; DestDir: "{app}\tools\drivers_can\Win32\C331"; Flags: ignoreversion
Source: "iCubProductionTestSuite\tools\drivers_can\Win32\C331\canc331.inf"; DestDir: "{app}\tools\drivers_can\Win32\C331"; Flags: ignoreversion
Source: "iCubProductionTestSuite\tools\drivers_can\Win32\C331\relnotes.html"; DestDir: "{app}\tools\drivers_can\Win32\C331"; Flags: ignoreversion
Source: "iCubProductionTestSuite\tools\drivers_can\Win32\C331\x86\c331.sys"; DestDir: "{app}\tools\drivers_can\Win32\C331\x86"; Flags: ignoreversion
Source: "iCubProductionTestSuite\tools\drivers_can\Win32\C331\x86\calcan32.dll"; DestDir: "{app}\tools\drivers_can\Win32\C331\x86"; Flags: ignoreversion
Source: "iCubProductionTestSuite\tools\drivers_can\Win32\C331\x86\canui32.dll"; DestDir: "{app}\tools\drivers_can\Win32\C331\x86"; Flags: ignoreversion
Source: "iCubProductionTestSuite\tools\drivers_can\Win32\C331\x86\ntcan.dll"; DestDir: "{app}\tools\drivers_can\Win32\C331\x86"; Flags: ignoreversion
Source: "iCubProductionTestSuite\tools\drivers_can\Win32\C360\canc360.inf"; DestDir: "{app}\tools\drivers_can\Win32\C360"; Flags: ignoreversion
Source: "iCubProductionTestSuite\tools\drivers_can\Win32\C360\Relnotes.html"; DestDir: "{app}\tools\drivers_can\Win32\C360"; Flags: ignoreversion
Source: "iCubProductionTestSuite\tools\drivers_can\Win32\C360\x86\c360.sys"; DestDir: "{app}\tools\drivers_can\Win32\C360\x86"; Flags: ignoreversion
Source: "iCubProductionTestSuite\tools\drivers_can\Win32\C360\x86\calcan32.dll"; DestDir: "{app}\tools\drivers_can\Win32\C360\x86"; Flags: ignoreversion
Source: "iCubProductionTestSuite\tools\drivers_can\Win32\C360\x86\canui32.dll"; DestDir: "{app}\tools\drivers_can\Win32\C360\x86"; Flags: ignoreversion
Source: "iCubProductionTestSuite\tools\drivers_can\Win32\C360\x86\ntcan.dll"; DestDir: "{app}\tools\drivers_can\Win32\C360\x86"; Flags: ignoreversion
Source: "iCubProductionTestSuite\tools\drivers_can\Win32\C360\x86\updc360.exe"; DestDir: "{app}\tools\drivers_can\Win32\C360\x86"; Flags: ignoreversion
Source: "iCubProductionTestSuite\tools\drivers_can\Win32\C360\x86\updc360.zip"; DestDir: "{app}\tools\drivers_can\Win32\C360\x86"; Flags: ignoreversion
Source: "iCubProductionTestSuite\tools\drivers_can\Win32\C400\canc400.cat"; DestDir: "{app}\tools\drivers_can\Win32\C400"; Flags: ignoreversion
Source: "iCubProductionTestSuite\tools\drivers_can\Win32\C400\canc400.inf"; DestDir: "{app}\tools\drivers_can\Win32\C400"; Flags: ignoreversion
Source: "iCubProductionTestSuite\tools\drivers_can\Win32\C400\relnotes.html"; DestDir: "{app}\tools\drivers_can\Win32\C400"; Flags: ignoreversion
Source: "iCubProductionTestSuite\tools\drivers_can\Win32\C400\x86\c400.sys"; DestDir: "{app}\tools\drivers_can\Win32\C400\x86"; Flags: ignoreversion
Source: "iCubProductionTestSuite\tools\drivers_can\Win32\C400\x86\calcan32.dll"; DestDir: "{app}\tools\drivers_can\Win32\C400\x86"; Flags: ignoreversion
Source: "iCubProductionTestSuite\tools\drivers_can\Win32\C400\x86\canui32.dll"; DestDir: "{app}\tools\drivers_can\Win32\C400\x86"; Flags: ignoreversion
Source: "iCubProductionTestSuite\tools\drivers_can\Win32\C400\x86\ntcan.dll"; DestDir: "{app}\tools\drivers_can\Win32\C400\x86"; Flags: ignoreversion
Source: "iCubProductionTestSuite\tools\drivers_can\Win32\C405\canc405.cat"; DestDir: "{app}\tools\drivers_can\Win32\C405"; Flags: ignoreversion
Source: "iCubProductionTestSuite\tools\drivers_can\Win32\C405\canc405.inf"; DestDir: "{app}\tools\drivers_can\Win32\C405"; Flags: ignoreversion
Source: "iCubProductionTestSuite\tools\drivers_can\Win32\C405\Readme.txt"; DestDir: "{app}\tools\drivers_can\Win32\C405"; Flags: ignoreversion
Source: "iCubProductionTestSuite\tools\drivers_can\Win32\C405\relnotes.html"; DestDir: "{app}\tools\drivers_can\Win32\C405"; Flags: ignoreversion
Source: "iCubProductionTestSuite\tools\drivers_can\Win32\C405\x86\calcan32.dll"; DestDir: "{app}\tools\drivers_can\Win32\C405\x86"; Flags: ignoreversion
Source: "iCubProductionTestSuite\tools\drivers_can\Win32\C405\x86\canui32.dll"; DestDir: "{app}\tools\drivers_can\Win32\C405\x86"; Flags: ignoreversion
Source: "iCubProductionTestSuite\tools\drivers_can\Win32\C405\x86\ntcan.dll"; DestDir: "{app}\tools\drivers_can\Win32\C405\x86"; Flags: ignoreversion
Source: "iCubProductionTestSuite\tools\drivers_can\Win32\C405\x86\pci405.sys"; DestDir: "{app}\tools\drivers_can\Win32\C405\x86"; Flags: ignoreversion
Source: "iCubProductionTestSuite\tools\drivers_can\Win32\USB1\canu331.inf"; DestDir: "{app}\tools\drivers_can\Win32\USB1"; Flags: ignoreversion
Source: "iCubProductionTestSuite\tools\drivers_can\Win32\USB1\Relnotes.html"; DestDir: "{app}\tools\drivers_can\Win32\USB1"; Flags: ignoreversion
Source: "iCubProductionTestSuite\tools\drivers_can\Win32\USB1\x86\calcan32.dll"; DestDir: "{app}\tools\drivers_can\Win32\USB1\x86"; Flags: ignoreversion
Source: "iCubProductionTestSuite\tools\drivers_can\Win32\USB1\x86\canui32.dll"; DestDir: "{app}\tools\drivers_can\Win32\USB1\x86"; Flags: ignoreversion
Source: "iCubProductionTestSuite\tools\drivers_can\Win32\USB1\x86\ntcan.dll"; DestDir: "{app}\tools\drivers_can\Win32\USB1\x86"; Flags: ignoreversion
Source: "iCubProductionTestSuite\tools\drivers_can\Win32\USB1\x86\updusb331.exe"; DestDir: "{app}\tools\drivers_can\Win32\USB1\x86"; Flags: ignoreversion
Source: "iCubProductionTestSuite\tools\drivers_can\Win32\USB1\x86\usb331.sys"; DestDir: "{app}\tools\drivers_can\Win32\USB1\x86"; Flags: ignoreversion
Source: "iCubProductionTestSuite\tools\drivers_can\Win32\USB2\canu2292.cat"; DestDir: "{app}\tools\drivers_can\Win32\USB2"; Flags: ignoreversion
Source: "iCubProductionTestSuite\tools\drivers_can\Win32\USB2\canu2292.inf"; DestDir: "{app}\tools\drivers_can\Win32\USB2"; Flags: ignoreversion
Source: "iCubProductionTestSuite\tools\drivers_can\Win32\USB2\relnotes.html"; DestDir: "{app}\tools\drivers_can\Win32\USB2"; Flags: ignoreversion
Source: "iCubProductionTestSuite\tools\drivers_can\Win32\USB2\x86\calcan32.dll"; DestDir: "{app}\tools\drivers_can\Win32\USB2\x86"; Flags: ignoreversion
Source: "iCubProductionTestSuite\tools\drivers_can\Win32\USB2\x86\canui32.dll"; DestDir: "{app}\tools\drivers_can\Win32\USB2\x86"; Flags: ignoreversion
Source: "iCubProductionTestSuite\tools\drivers_can\Win32\USB2\x86\ntcan.dll"; DestDir: "{app}\tools\drivers_can\Win32\USB2\x86"; Flags: ignoreversion
Source: "iCubProductionTestSuite\tools\drivers_can\Win32\USB2\x86\usb2292.sys"; DestDir: "{app}\tools\drivers_can\Win32\USB2\x86"; Flags: ignoreversion
Source: "iCubProductionTestSuite\tools\drivers_can\Win64\C200\canc200a.cat"; DestDir: "{app}\tools\drivers_can\Win64\C200"; Flags: ignoreversion
Source: "iCubProductionTestSuite\tools\drivers_can\Win64\C200\canc200a.inf"; DestDir: "{app}\tools\drivers_can\Win64\C200"; Flags: ignoreversion
Source: "iCubProductionTestSuite\tools\drivers_can\Win64\C200\relnotes.html"; DestDir: "{app}\tools\drivers_can\Win64\C200"; Flags: ignoreversion
Source: "iCubProductionTestSuite\tools\drivers_can\Win64\C200\amd64\c200a.sys"; DestDir: "{app}\tools\drivers_can\Win64\C200\amd64"; Flags: ignoreversion
Source: "iCubProductionTestSuite\tools\drivers_can\Win64\C200\amd64\calcan64.dll"; DestDir: "{app}\tools\drivers_can\Win64\C200\amd64"; Flags: ignoreversion
Source: "iCubProductionTestSuite\tools\drivers_can\Win64\C200\amd64\canui64.dll"; DestDir: "{app}\tools\drivers_can\Win64\C200\amd64"; Flags: ignoreversion
Source: "iCubProductionTestSuite\tools\drivers_can\Win64\C200\amd64\ntcan64.dll"; DestDir: "{app}\tools\drivers_can\Win64\C200\amd64"; Flags: ignoreversion
Source: "iCubProductionTestSuite\tools\drivers_can\Win64\C200\x86\calcan32.dll"; DestDir: "{app}\tools\drivers_can\Win64\C200\x86"; Flags: ignoreversion
Source: "iCubProductionTestSuite\tools\drivers_can\Win64\C200\x86\ntcan.dll"; DestDir: "{app}\tools\drivers_can\Win64\C200\x86"; Flags: ignoreversion
Source: "iCubProductionTestSuite\tools\drivers_can\Win64\C331\canc331a.cat"; DestDir: "{app}\tools\drivers_can\Win64\C331"; Flags: ignoreversion
Source: "iCubProductionTestSuite\tools\drivers_can\Win64\C331\canc331a.inf"; DestDir: "{app}\tools\drivers_can\Win64\C331"; Flags: ignoreversion
Source: "iCubProductionTestSuite\tools\drivers_can\Win64\C331\relnotes.html"; DestDir: "{app}\tools\drivers_can\Win64\C331"; Flags: ignoreversion
Source: "iCubProductionTestSuite\tools\drivers_can\Win64\C331\amd64\c331a.sys"; DestDir: "{app}\tools\drivers_can\Win64\C331\amd64"; Flags: ignoreversion
Source: "iCubProductionTestSuite\tools\drivers_can\Win64\C331\amd64\calcan64.dll"; DestDir: "{app}\tools\drivers_can\Win64\C331\amd64"; Flags: ignoreversion
Source: "iCubProductionTestSuite\tools\drivers_can\Win64\C331\amd64\canui64.dll"; DestDir: "{app}\tools\drivers_can\Win64\C331\amd64"; Flags: ignoreversion
Source: "iCubProductionTestSuite\tools\drivers_can\Win64\C331\amd64\ntcan64.dll"; DestDir: "{app}\tools\drivers_can\Win64\C331\amd64"; Flags: ignoreversion
Source: "iCubProductionTestSuite\tools\drivers_can\Win64\C331\x86\calcan32.dll"; DestDir: "{app}\tools\drivers_can\Win64\C331\x86"; Flags: ignoreversion
Source: "iCubProductionTestSuite\tools\drivers_can\Win64\C331\x86\ntcan.dll"; DestDir: "{app}\tools\drivers_can\Win64\C331\x86"; Flags: ignoreversion
Source: "iCubProductionTestSuite\tools\drivers_can\Win64\C360\canc360a.cat"; DestDir: "{app}\tools\drivers_can\Win64\C360"; Flags: ignoreversion
Source: "iCubProductionTestSuite\tools\drivers_can\Win64\C360\canc360a.inf"; DestDir: "{app}\tools\drivers_can\Win64\C360"; Flags: ignoreversion
Source: "iCubProductionTestSuite\tools\drivers_can\Win64\C360\Relnotes.html"; DestDir: "{app}\tools\drivers_can\Win64\C360"; Flags: ignoreversion
Source: "iCubProductionTestSuite\tools\drivers_can\Win64\C360\amd64\c360a.sys"; DestDir: "{app}\tools\drivers_can\Win64\C360\amd64"; Flags: ignoreversion
Source: "iCubProductionTestSuite\tools\drivers_can\Win64\C360\amd64\calcan64.dll"; DestDir: "{app}\tools\drivers_can\Win64\C360\amd64"; Flags: ignoreversion
Source: "iCubProductionTestSuite\tools\drivers_can\Win64\C360\amd64\canui64.dll"; DestDir: "{app}\tools\drivers_can\Win64\C360\amd64"; Flags: ignoreversion
Source: "iCubProductionTestSuite\tools\drivers_can\Win64\C360\amd64\ntcan64.dll"; DestDir: "{app}\tools\drivers_can\Win64\C360\amd64"; Flags: ignoreversion
Source: "iCubProductionTestSuite\tools\drivers_can\Win64\C360\x86\calcan32.dll"; DestDir: "{app}\tools\drivers_can\Win64\C360\x86"; Flags: ignoreversion
Source: "iCubProductionTestSuite\tools\drivers_can\Win64\C360\x86\ntcan.dll"; DestDir: "{app}\tools\drivers_can\Win64\C360\x86"; Flags: ignoreversion
Source: "iCubProductionTestSuite\tools\drivers_can\Win64\C360\x86\updc360.exe"; DestDir: "{app}\tools\drivers_can\Win64\C360\x86"; Flags: ignoreversion
Source: "iCubProductionTestSuite\tools\drivers_can\Win64\C400\canc400a.cat"; DestDir: "{app}\tools\drivers_can\Win64\C400"; Flags: ignoreversion
Source: "iCubProductionTestSuite\tools\drivers_can\Win64\C400\canc400a.inf"; DestDir: "{app}\tools\drivers_can\Win64\C400"; Flags: ignoreversion
Source: "iCubProductionTestSuite\tools\drivers_can\Win64\C400\relnotes.html"; DestDir: "{app}\tools\drivers_can\Win64\C400"; Flags: ignoreversion
Source: "iCubProductionTestSuite\tools\drivers_can\Win64\C400\amd64\c400a.sys"; DestDir: "{app}\tools\drivers_can\Win64\C400\amd64"; Flags: ignoreversion
Source: "iCubProductionTestSuite\tools\drivers_can\Win64\C400\amd64\calcan64.dll"; DestDir: "{app}\tools\drivers_can\Win64\C400\amd64"; Flags: ignoreversion
Source: "iCubProductionTestSuite\tools\drivers_can\Win64\C400\amd64\canui64.dll"; DestDir: "{app}\tools\drivers_can\Win64\C400\amd64"; Flags: ignoreversion
Source: "iCubProductionTestSuite\tools\drivers_can\Win64\C400\amd64\ntcan64.dll"; DestDir: "{app}\tools\drivers_can\Win64\C400\amd64"; Flags: ignoreversion
Source: "iCubProductionTestSuite\tools\drivers_can\Win64\C400\x86\calcan32.dll"; DestDir: "{app}\tools\drivers_can\Win64\C400\x86"; Flags: ignoreversion
Source: "iCubProductionTestSuite\tools\drivers_can\Win64\C400\x86\ntcan.dll"; DestDir: "{app}\tools\drivers_can\Win64\C400\x86"; Flags: ignoreversion
Source: "iCubProductionTestSuite\tools\drivers_can\Win64\C405\canc405.cat"; DestDir: "{app}\tools\drivers_can\Win64\C405"; Flags: ignoreversion
Source: "iCubProductionTestSuite\tools\drivers_can\Win64\C405\canc405.inf"; DestDir: "{app}\tools\drivers_can\Win64\C405"; Flags: ignoreversion
Source: "iCubProductionTestSuite\tools\drivers_can\Win64\C405\Readme.txt"; DestDir: "{app}\tools\drivers_can\Win64\C405"; Flags: ignoreversion
Source: "iCubProductionTestSuite\tools\drivers_can\Win64\C405\relnotes.html"; DestDir: "{app}\tools\drivers_can\Win64\C405"; Flags: ignoreversion
Source: "iCubProductionTestSuite\tools\drivers_can\Win64\C405\x86\calcan32.dll"; DestDir: "{app}\tools\drivers_can\Win64\C405\x86"; Flags: ignoreversion
Source: "iCubProductionTestSuite\tools\drivers_can\Win64\C405\x86\canui32.dll"; DestDir: "{app}\tools\drivers_can\Win64\C405\x86"; Flags: ignoreversion
Source: "iCubProductionTestSuite\tools\drivers_can\Win64\C405\x86\ntcan.dll"; DestDir: "{app}\tools\drivers_can\Win64\C405\x86"; Flags: ignoreversion
Source: "iCubProductionTestSuite\tools\drivers_can\Win64\C405\x86\pci405.sys"; DestDir: "{app}\tools\drivers_can\Win64\C405\x86"; Flags: ignoreversion
Source: "iCubProductionTestSuite\tools\drivers_can\Win64\USB1\canu331a.cat"; DestDir: "{app}\tools\drivers_can\Win64\USB1"; Flags: ignoreversion
Source: "iCubProductionTestSuite\tools\drivers_can\Win64\USB1\canu331a.inf"; DestDir: "{app}\tools\drivers_can\Win64\USB1"; Flags: ignoreversion
Source: "iCubProductionTestSuite\tools\drivers_can\Win64\USB1\Relnotes.html"; DestDir: "{app}\tools\drivers_can\Win64\USB1"; Flags: ignoreversion
Source: "iCubProductionTestSuite\tools\drivers_can\Win64\USB1\amd64\calcan64.dll"; DestDir: "{app}\tools\drivers_can\Win64\USB1\amd64"; Flags: ignoreversion
Source: "iCubProductionTestSuite\tools\drivers_can\Win64\USB1\amd64\canui64.dll"; DestDir: "{app}\tools\drivers_can\Win64\USB1\amd64"; Flags: ignoreversion
Source: "iCubProductionTestSuite\tools\drivers_can\Win64\USB1\amd64\ntcan64.dll"; DestDir: "{app}\tools\drivers_can\Win64\USB1\amd64"; Flags: ignoreversion
Source: "iCubProductionTestSuite\tools\drivers_can\Win64\USB1\amd64\usb331a.sys"; DestDir: "{app}\tools\drivers_can\Win64\USB1\amd64"; Flags: ignoreversion
Source: "iCubProductionTestSuite\tools\drivers_can\Win64\USB1\x86\calcan32.dll"; DestDir: "{app}\tools\drivers_can\Win64\USB1\x86"; Flags: ignoreversion
Source: "iCubProductionTestSuite\tools\drivers_can\Win64\USB1\x86\ntcan.dll"; DestDir: "{app}\tools\drivers_can\Win64\USB1\x86"; Flags: ignoreversion
Source: "iCubProductionTestSuite\tools\drivers_can\Win64\USB1\x86\updusb331.exe"; DestDir: "{app}\tools\drivers_can\Win64\USB1\x86"; Flags: ignoreversion
Source: "iCubProductionTestSuite\tools\drivers_can\Win64\USB2\canu2292a.cat"; DestDir: "{app}\tools\drivers_can\Win64\USB2"; Flags: ignoreversion
Source: "iCubProductionTestSuite\tools\drivers_can\Win64\USB2\canu2292a.inf"; DestDir: "{app}\tools\drivers_can\Win64\USB2"; Flags: ignoreversion
Source: "iCubProductionTestSuite\tools\drivers_can\Win64\USB2\relnotes.html"; DestDir: "{app}\tools\drivers_can\Win64\USB2"; Flags: ignoreversion
Source: "iCubProductionTestSuite\tools\drivers_can\Win64\USB2\amd64\calcan64.dll"; DestDir: "{app}\tools\drivers_can\Win64\USB2\amd64"; Flags: ignoreversion
Source: "iCubProductionTestSuite\tools\drivers_can\Win64\USB2\amd64\canui64.dll"; DestDir: "{app}\tools\drivers_can\Win64\USB2\amd64"; Flags: ignoreversion
Source: "iCubProductionTestSuite\tools\drivers_can\Win64\USB2\amd64\ntcan64.dll"; DestDir: "{app}\tools\drivers_can\Win64\USB2\amd64"; Flags: ignoreversion
Source: "iCubProductionTestSuite\tools\drivers_can\Win64\USB2\amd64\usb2292a.sys"; DestDir: "{app}\tools\drivers_can\Win64\USB2\amd64"; Flags: ignoreversion
Source: "iCubProductionTestSuite\tools\drivers_can\Win64\USB2\x86\calcan32.dll"; DestDir: "{app}\tools\drivers_can\Win64\USB2\x86"; Flags: ignoreversion
Source: "iCubProductionTestSuite\tools\drivers_can\Win64\USB2\x86\ntcan.dll"; DestDir: "{app}\tools\drivers_can\Win64\USB2\x86"; Flags: ignoreversion
Source: "iCubProductionTestSuite\tools\drivers_can\Win9x\calcan32.dll"; DestDir: "{app}\tools\drivers_can\Win9x"; Flags: ignoreversion
Source: "iCubProductionTestSuite\tools\drivers_can\Win9x\canesd.inf"; DestDir: "{app}\tools\drivers_can\Win9x"; Flags: ignoreversion
Source: "iCubProductionTestSuite\tools\drivers_can\Win9x\canui.dll"; DestDir: "{app}\tools\drivers_can\Win9x"; Flags: ignoreversion
Source: "iCubProductionTestSuite\tools\drivers_can\Win9x\cpcc.exe"; DestDir: "{app}\tools\drivers_can\Win9x"; Flags: ignoreversion
Source: "iCubProductionTestSuite\tools\drivers_can\Win9x\CPCC.vxd"; DestDir: "{app}\tools\drivers_can\Win9x"; Flags: ignoreversion
Source: "iCubProductionTestSuite\tools\drivers_can\Win9x\dnet.dll"; DestDir: "{app}\tools\drivers_can\Win9x"; Flags: ignoreversion
Source: "iCubProductionTestSuite\tools\drivers_can\Win9x\isa200.vxd"; DestDir: "{app}\tools\drivers_can\Win9x"; Flags: ignoreversion
Source: "iCubProductionTestSuite\tools\drivers_can\Win9x\isa200b.vxd"; DestDir: "{app}\tools\drivers_can\Win9x"; Flags: ignoreversion
Source: "iCubProductionTestSuite\tools\drivers_can\Win9x\ISA331.vxd"; DestDir: "{app}\tools\drivers_can\Win9x"; Flags: ignoreversion
Source: "iCubProductionTestSuite\tools\drivers_can\Win9x\NTCAN.DLL"; DestDir: "{app}\tools\drivers_can\Win9x"; Flags: ignoreversion
Source: "iCubProductionTestSuite\tools\drivers_can\Win9x\pc104331.vxd"; DestDir: "{app}\tools\drivers_can\Win9x"; Flags: ignoreversion
Source: "iCubProductionTestSuite\tools\drivers_can\Win9x\pci200.vxd"; DestDir: "{app}\tools\drivers_can\Win9x"; Flags: ignoreversion
Source: "iCubProductionTestSuite\tools\drivers_can\Win9x\PCI331.vxd"; DestDir: "{app}\tools\drivers_can\Win9x"; Flags: ignoreversion
Source: "iCubProductionTestSuite\tools\drivers_can\Win9x\PCI360.vxd"; DestDir: "{app}\tools\drivers_can\Win9x"; Flags: ignoreversion
Source: "iCubProductionTestSuite\tools\drivers_can\Win9x\plx9052.reg"; DestDir: "{app}\tools\drivers_can\Win9x"; Flags: ignoreversion
Source: "iCubProductionTestSuite\tools\drivers_can\Win9x\Relnotes.htm"; DestDir: "{app}\tools\drivers_can\Win9x"; Flags: ignoreversion
Source: "iCubProductionTestSuite\tools\drivers_can\Win9x\updc331.exe"; DestDir: "{app}\tools\drivers_can\Win9x"; Flags: ignoreversion
Source: "iCubProductionTestSuite\tools\drivers_can\Win9x\updc331i.exe"; DestDir: "{app}\tools\drivers_can\Win9x"; Flags: ignoreversion
Source: "iCubProductionTestSuite\tools\drivers_can\Win9x\updc360.exe"; DestDir: "{app}\tools\drivers_can\Win9x"; Flags: ignoreversion
Source: "iCubProductionTestSuite\tools\drivers_can\Win9x\usb331.sys"; DestDir: "{app}\tools\drivers_can\Win9x"; Flags: ignoreversion
Source: "iCubProductionTestSuite\tools\drivers_can\WinNT\CPCC\DATA.TAG"; DestDir: "{app}\tools\drivers_can\WinNT\CPCC"; Flags: ignoreversion
Source: "iCubProductionTestSuite\tools\drivers_can\WinNT\CPCC\data1.cab"; DestDir: "{app}\tools\drivers_can\WinNT\CPCC"; Flags: ignoreversion
Source: "iCubProductionTestSuite\tools\drivers_can\WinNT\CPCC\lang.dat"; DestDir: "{app}\tools\drivers_can\WinNT\CPCC"; Flags: ignoreversion
Source: "iCubProductionTestSuite\tools\drivers_can\WinNT\CPCC\layout.bin"; DestDir: "{app}\tools\drivers_can\WinNT\CPCC"; Flags: ignoreversion
Source: "iCubProductionTestSuite\tools\drivers_can\WinNT\CPCC\os.dat"; DestDir: "{app}\tools\drivers_can\WinNT\CPCC"; Flags: ignoreversion
Source: "iCubProductionTestSuite\tools\drivers_can\WinNT\CPCC\SETUP.EXE"; DestDir: "{app}\tools\drivers_can\WinNT\CPCC"; Flags: ignoreversion
Source: "iCubProductionTestSuite\tools\drivers_can\WinNT\CPCC\SETUP.INI"; DestDir: "{app}\tools\drivers_can\WinNT\CPCC"; Flags: ignoreversion
Source: "iCubProductionTestSuite\tools\drivers_can\WinNT\CPCC\setup.ins"; DestDir: "{app}\tools\drivers_can\WinNT\CPCC"; Flags: ignoreversion
Source: "iCubProductionTestSuite\tools\drivers_can\WinNT\CPCC\setup.lid"; DestDir: "{app}\tools\drivers_can\WinNT\CPCC"; Flags: ignoreversion
Source: "iCubProductionTestSuite\tools\drivers_can\WinNT\CPCC\_INST32I.EX_"; DestDir: "{app}\tools\drivers_can\WinNT\CPCC"; Flags: ignoreversion
Source: "iCubProductionTestSuite\tools\drivers_can\WinNT\CPCC\_ISDEL.EXE"; DestDir: "{app}\tools\drivers_can\WinNT\CPCC"; Flags: ignoreversion
Source: "iCubProductionTestSuite\tools\drivers_can\WinNT\CPCC\_setup.dll"; DestDir: "{app}\tools\drivers_can\WinNT\CPCC"; Flags: ignoreversion
Source: "iCubProductionTestSuite\tools\drivers_can\WinNT\CPCC\_sys1.cab"; DestDir: "{app}\tools\drivers_can\WinNT\CPCC"; Flags: ignoreversion
Source: "iCubProductionTestSuite\tools\drivers_can\WinNT\CPCC\_user1.cab"; DestDir: "{app}\tools\drivers_can\WinNT\CPCC"; Flags: ignoreversion
Source: "iCubProductionTestSuite\tools\drivers_can\WinNT\CPCI331\setup.bat"; DestDir: "{app}\tools\drivers_can\WinNT\CPCI331"; Flags: ignoreversion
Source: "iCubProductionTestSuite\tools\drivers_can\WinNT\CPCI360\setup.bat"; DestDir: "{app}\tools\drivers_can\WinNT\CPCI360"; Flags: ignoreversion
Source: "iCubProductionTestSuite\tools\drivers_can\WinNT\ISA200\DATA.TAG"; DestDir: "{app}\tools\drivers_can\WinNT\ISA200"; Flags: ignoreversion
Source: "iCubProductionTestSuite\tools\drivers_can\WinNT\ISA200\data1.cab"; DestDir: "{app}\tools\drivers_can\WinNT\ISA200"; Flags: ignoreversion
Source: "iCubProductionTestSuite\tools\drivers_can\WinNT\ISA200\lang.dat"; DestDir: "{app}\tools\drivers_can\WinNT\ISA200"; Flags: ignoreversion
Source: "iCubProductionTestSuite\tools\drivers_can\WinNT\ISA200\layout.bin"; DestDir: "{app}\tools\drivers_can\WinNT\ISA200"; Flags: ignoreversion
Source: "iCubProductionTestSuite\tools\drivers_can\WinNT\ISA200\os.dat"; DestDir: "{app}\tools\drivers_can\WinNT\ISA200"; Flags: ignoreversion
Source: "iCubProductionTestSuite\tools\drivers_can\WinNT\ISA200\SETUP.EXE"; DestDir: "{app}\tools\drivers_can\WinNT\ISA200"; Flags: ignoreversion
Source: "iCubProductionTestSuite\tools\drivers_can\WinNT\ISA200\SETUP.INI"; DestDir: "{app}\tools\drivers_can\WinNT\ISA200"; Flags: ignoreversion
Source: "iCubProductionTestSuite\tools\drivers_can\WinNT\ISA200\setup.ins"; DestDir: "{app}\tools\drivers_can\WinNT\ISA200"; Flags: ignoreversion
Source: "iCubProductionTestSuite\tools\drivers_can\WinNT\ISA200\setup.lid"; DestDir: "{app}\tools\drivers_can\WinNT\ISA200"; Flags: ignoreversion
Source: "iCubProductionTestSuite\tools\drivers_can\WinNT\ISA200\_INST32I.EX_"; DestDir: "{app}\tools\drivers_can\WinNT\ISA200"; Flags: ignoreversion
Source: "iCubProductionTestSuite\tools\drivers_can\WinNT\ISA200\_ISDEL.EXE"; DestDir: "{app}\tools\drivers_can\WinNT\ISA200"; Flags: ignoreversion
Source: "iCubProductionTestSuite\tools\drivers_can\WinNT\ISA200\_setup.dll"; DestDir: "{app}\tools\drivers_can\WinNT\ISA200"; Flags: ignoreversion
Source: "iCubProductionTestSuite\tools\drivers_can\WinNT\ISA200\_sys1.cab"; DestDir: "{app}\tools\drivers_can\WinNT\ISA200"; Flags: ignoreversion
Source: "iCubProductionTestSuite\tools\drivers_can\WinNT\ISA200\_user1.cab"; DestDir: "{app}\tools\drivers_can\WinNT\ISA200"; Flags: ignoreversion
Source: "iCubProductionTestSuite\tools\drivers_can\WinNT\ISA331\DATA.TAG"; DestDir: "{app}\tools\drivers_can\WinNT\ISA331"; Flags: ignoreversion
Source: "iCubProductionTestSuite\tools\drivers_can\WinNT\ISA331\data1.cab"; DestDir: "{app}\tools\drivers_can\WinNT\ISA331"; Flags: ignoreversion
Source: "iCubProductionTestSuite\tools\drivers_can\WinNT\ISA331\lang.dat"; DestDir: "{app}\tools\drivers_can\WinNT\ISA331"; Flags: ignoreversion
Source: "iCubProductionTestSuite\tools\drivers_can\WinNT\ISA331\layout.bin"; DestDir: "{app}\tools\drivers_can\WinNT\ISA331"; Flags: ignoreversion
Source: "iCubProductionTestSuite\tools\drivers_can\WinNT\ISA331\os.dat"; DestDir: "{app}\tools\drivers_can\WinNT\ISA331"; Flags: ignoreversion
Source: "iCubProductionTestSuite\tools\drivers_can\WinNT\ISA331\SETUP.EXE"; DestDir: "{app}\tools\drivers_can\WinNT\ISA331"; Flags: ignoreversion
Source: "iCubProductionTestSuite\tools\drivers_can\WinNT\ISA331\SETUP.INI"; DestDir: "{app}\tools\drivers_can\WinNT\ISA331"; Flags: ignoreversion
Source: "iCubProductionTestSuite\tools\drivers_can\WinNT\ISA331\setup.ins"; DestDir: "{app}\tools\drivers_can\WinNT\ISA331"; Flags: ignoreversion
Source: "iCubProductionTestSuite\tools\drivers_can\WinNT\ISA331\setup.lid"; DestDir: "{app}\tools\drivers_can\WinNT\ISA331"; Flags: ignoreversion
Source: "iCubProductionTestSuite\tools\drivers_can\WinNT\ISA331\_INST32I.EX_"; DestDir: "{app}\tools\drivers_can\WinNT\ISA331"; Flags: ignoreversion
Source: "iCubProductionTestSuite\tools\drivers_can\WinNT\ISA331\_ISDEL.EXE"; DestDir: "{app}\tools\drivers_can\WinNT\ISA331"; Flags: ignoreversion
Source: "iCubProductionTestSuite\tools\drivers_can\WinNT\ISA331\_setup.dll"; DestDir: "{app}\tools\drivers_can\WinNT\ISA331"; Flags: ignoreversion
Source: "iCubProductionTestSuite\tools\drivers_can\WinNT\ISA331\_sys1.cab"; DestDir: "{app}\tools\drivers_can\WinNT\ISA331"; Flags: ignoreversion
Source: "iCubProductionTestSuite\tools\drivers_can\WinNT\ISA331\_user1.cab"; DestDir: "{app}\tools\drivers_can\WinNT\ISA331"; Flags: ignoreversion
Source: "iCubProductionTestSuite\tools\drivers_can\WinNT\PC104200\setup.bat"; DestDir: "{app}\tools\drivers_can\WinNT\PC104200"; Flags: ignoreversion
Source: "iCubProductionTestSuite\tools\drivers_can\WinNT\Pc104331\setup.bat"; DestDir: "{app}\tools\drivers_can\WinNT\Pc104331"; Flags: ignoreversion
Source: "iCubProductionTestSuite\tools\drivers_can\WinNT\PCI200\DATA.TAG"; DestDir: "{app}\tools\drivers_can\WinNT\PCI200"; Flags: ignoreversion
Source: "iCubProductionTestSuite\tools\drivers_can\WinNT\PCI200\data1.cab"; DestDir: "{app}\tools\drivers_can\WinNT\PCI200"; Flags: ignoreversion
Source: "iCubProductionTestSuite\tools\drivers_can\WinNT\PCI200\lang.dat"; DestDir: "{app}\tools\drivers_can\WinNT\PCI200"; Flags: ignoreversion
Source: "iCubProductionTestSuite\tools\drivers_can\WinNT\PCI200\layout.bin"; DestDir: "{app}\tools\drivers_can\WinNT\PCI200"; Flags: ignoreversion
Source: "iCubProductionTestSuite\tools\drivers_can\WinNT\PCI200\os.dat"; DestDir: "{app}\tools\drivers_can\WinNT\PCI200"; Flags: ignoreversion
Source: "iCubProductionTestSuite\tools\drivers_can\WinNT\PCI200\SETUP.EXE"; DestDir: "{app}\tools\drivers_can\WinNT\PCI200"; Flags: ignoreversion
Source: "iCubProductionTestSuite\tools\drivers_can\WinNT\PCI200\SETUP.INI"; DestDir: "{app}\tools\drivers_can\WinNT\PCI200"; Flags: ignoreversion
Source: "iCubProductionTestSuite\tools\drivers_can\WinNT\PCI200\setup.ins"; DestDir: "{app}\tools\drivers_can\WinNT\PCI200"; Flags: ignoreversion
Source: "iCubProductionTestSuite\tools\drivers_can\WinNT\PCI200\setup.lid"; DestDir: "{app}\tools\drivers_can\WinNT\PCI200"; Flags: ignoreversion
Source: "iCubProductionTestSuite\tools\drivers_can\WinNT\PCI200\_INST32I.EX_"; DestDir: "{app}\tools\drivers_can\WinNT\PCI200"; Flags: ignoreversion
Source: "iCubProductionTestSuite\tools\drivers_can\WinNT\PCI200\_ISDEL.EXE"; DestDir: "{app}\tools\drivers_can\WinNT\PCI200"; Flags: ignoreversion
Source: "iCubProductionTestSuite\tools\drivers_can\WinNT\PCI200\_setup.dll"; DestDir: "{app}\tools\drivers_can\WinNT\PCI200"; Flags: ignoreversion
Source: "iCubProductionTestSuite\tools\drivers_can\WinNT\PCI200\_sys1.cab"; DestDir: "{app}\tools\drivers_can\WinNT\PCI200"; Flags: ignoreversion
Source: "iCubProductionTestSuite\tools\drivers_can\WinNT\PCI200\_user1.cab"; DestDir: "{app}\tools\drivers_can\WinNT\PCI200"; Flags: ignoreversion
Source: "iCubProductionTestSuite\tools\drivers_can\WinNT\PCI331\DATA.TAG"; DestDir: "{app}\tools\drivers_can\WinNT\PCI331"; Flags: ignoreversion
Source: "iCubProductionTestSuite\tools\drivers_can\WinNT\PCI331\data1.cab"; DestDir: "{app}\tools\drivers_can\WinNT\PCI331"; Flags: ignoreversion
Source: "iCubProductionTestSuite\tools\drivers_can\WinNT\PCI331\lang.dat"; DestDir: "{app}\tools\drivers_can\WinNT\PCI331"; Flags: ignoreversion
Source: "iCubProductionTestSuite\tools\drivers_can\WinNT\PCI331\layout.bin"; DestDir: "{app}\tools\drivers_can\WinNT\PCI331"; Flags: ignoreversion
Source: "iCubProductionTestSuite\tools\drivers_can\WinNT\PCI331\os.dat"; DestDir: "{app}\tools\drivers_can\WinNT\PCI331"; Flags: ignoreversion
Source: "iCubProductionTestSuite\tools\drivers_can\WinNT\PCI331\SETUP.EXE"; DestDir: "{app}\tools\drivers_can\WinNT\PCI331"; Flags: ignoreversion
Source: "iCubProductionTestSuite\tools\drivers_can\WinNT\PCI331\SETUP.INI"; DestDir: "{app}\tools\drivers_can\WinNT\PCI331"; Flags: ignoreversion
Source: "iCubProductionTestSuite\tools\drivers_can\WinNT\PCI331\setup.ins"; DestDir: "{app}\tools\drivers_can\WinNT\PCI331"; Flags: ignoreversion
Source: "iCubProductionTestSuite\tools\drivers_can\WinNT\PCI331\setup.lid"; DestDir: "{app}\tools\drivers_can\WinNT\PCI331"; Flags: ignoreversion
Source: "iCubProductionTestSuite\tools\drivers_can\WinNT\PCI331\_INST32I.EX_"; DestDir: "{app}\tools\drivers_can\WinNT\PCI331"; Flags: ignoreversion
Source: "iCubProductionTestSuite\tools\drivers_can\WinNT\PCI331\_ISDEL.EXE"; DestDir: "{app}\tools\drivers_can\WinNT\PCI331"; Flags: ignoreversion
Source: "iCubProductionTestSuite\tools\drivers_can\WinNT\PCI331\_setup.dll"; DestDir: "{app}\tools\drivers_can\WinNT\PCI331"; Flags: ignoreversion
Source: "iCubProductionTestSuite\tools\drivers_can\WinNT\PCI331\_sys1.cab"; DestDir: "{app}\tools\drivers_can\WinNT\PCI331"; Flags: ignoreversion
Source: "iCubProductionTestSuite\tools\drivers_can\WinNT\PCI331\_user1.cab"; DestDir: "{app}\tools\drivers_can\WinNT\PCI331"; Flags: ignoreversion
Source: "iCubProductionTestSuite\tools\drivers_can\WinNT\PCI360\DATA.TAG"; DestDir: "{app}\tools\drivers_can\WinNT\PCI360"; Flags: ignoreversion
Source: "iCubProductionTestSuite\tools\drivers_can\WinNT\PCI360\data1.cab"; DestDir: "{app}\tools\drivers_can\WinNT\PCI360"; Flags: ignoreversion
Source: "iCubProductionTestSuite\tools\drivers_can\WinNT\PCI360\lang.dat"; DestDir: "{app}\tools\drivers_can\WinNT\PCI360"; Flags: ignoreversion
Source: "iCubProductionTestSuite\tools\drivers_can\WinNT\PCI360\layout.bin"; DestDir: "{app}\tools\drivers_can\WinNT\PCI360"; Flags: ignoreversion
Source: "iCubProductionTestSuite\tools\drivers_can\WinNT\PCI360\os.dat"; DestDir: "{app}\tools\drivers_can\WinNT\PCI360"; Flags: ignoreversion
Source: "iCubProductionTestSuite\tools\drivers_can\WinNT\PCI360\SETUP.EXE"; DestDir: "{app}\tools\drivers_can\WinNT\PCI360"; Flags: ignoreversion
Source: "iCubProductionTestSuite\tools\drivers_can\WinNT\PCI360\SETUP.INI"; DestDir: "{app}\tools\drivers_can\WinNT\PCI360"; Flags: ignoreversion
Source: "iCubProductionTestSuite\tools\drivers_can\WinNT\PCI360\setup.ins"; DestDir: "{app}\tools\drivers_can\WinNT\PCI360"; Flags: ignoreversion
Source: "iCubProductionTestSuite\tools\drivers_can\WinNT\PCI360\setup.lid"; DestDir: "{app}\tools\drivers_can\WinNT\PCI360"; Flags: ignoreversion
Source: "iCubProductionTestSuite\tools\drivers_can\WinNT\PCI360\_INST32I.EX_"; DestDir: "{app}\tools\drivers_can\WinNT\PCI360"; Flags: ignoreversion
Source: "iCubProductionTestSuite\tools\drivers_can\WinNT\PCI360\_ISDEL.EXE"; DestDir: "{app}\tools\drivers_can\WinNT\PCI360"; Flags: ignoreversion
Source: "iCubProductionTestSuite\tools\drivers_can\WinNT\PCI360\_setup.dll"; DestDir: "{app}\tools\drivers_can\WinNT\PCI360"; Flags: ignoreversion
Source: "iCubProductionTestSuite\tools\drivers_can\WinNT\PCI360\_sys1.cab"; DestDir: "{app}\tools\drivers_can\WinNT\PCI360"; Flags: ignoreversion
Source: "iCubProductionTestSuite\tools\drivers_can\WinNT\PCI360\_user1.cab"; DestDir: "{app}\tools\drivers_can\WinNT\PCI360"; Flags: ignoreversion
Source: "iCubProductionTestSuite\img\clean-button.png"; DestDir: "{app}\img"; Flags: ignoreversion
Source: "iCubProductionTestSuite\img\clear.png"; DestDir: "{app}\img"; Flags: ignoreversion
Source: "iCubProductionTestSuite\img\download-button.png"; DestDir: "{app}\img"; Flags: ignoreversion
Source: "iCubProductionTestSuite\img\icub.ico"; DestDir: "{app}\img"; Flags: ignoreversion
Source: "iCubProductionTestSuite\img\iit-logo-icub.png"; DestDir: "{app}\img"; Flags: ignoreversion
Source: "iCubProductionTestSuite\img\logo.jpg"; DestDir: "{app}\img"; Flags: ignoreversion
Source: "iCubProductionTestSuite\img\LOGO.png"; DestDir: "{app}\img"; Flags: ignoreversion
Source: "iCubProductionTestSuite\img\play-button.png"; DestDir: "{app}\img"; Flags: ignoreversion
Source: "iCubProductionTestSuite\img\stop-button.png"; DestDir: "{app}\img"; Flags: ignoreversion
Source: "iCubProductionTestSuite\img\user.png"; DestDir: "{app}\img"; Flags: ignoreversion
Source: "iCubProductionTestSuite\img\brushlessMotors\assembly.jpg"; DestDir: "{app}\img\brushlessMotors"; Flags: ignoreversion
Source: "iCubProductionTestSuite\img\brushlessMotors\avvolgimenti.jpg"; DestDir: "{app}\img\brushlessMotors"; Flags: ignoreversion
Source: "iCubProductionTestSuite\img\brushlessMotors\fasatura.jpg"; DestDir: "{app}\img\brushlessMotors"; Flags: ignoreversion
Source: "iCubProductionTestSuite\img\brushlessMotors\hall.jpg"; DestDir: "{app}\img\brushlessMotors"; Flags: ignoreversion
Source: "iCubProductionTestSuite\img\brushlessMotors\motor.jpg"; DestDir: "{app}\img\brushlessMotors"; Flags: ignoreversion
Source: "iCubProductionTestSuite\img\brushlessMotors\setup.jpg"; DestDir: "{app}\img\brushlessMotors"; Flags: ignoreversion
Source: "iCubProductionTestSuite\img\brushlessMotors\valori.jpg"; DestDir: "{app}\img\brushlessMotors"; Flags: ignoreversion
Source: "iCubProductionTestSuite\img\brushlessMotors\allineamento-albero-rotore.png"; DestDir: "{app}\img\brushlessMotors"; Flags: ignoreversion
Source: "iCubProductionTestSuite\img\dcMotors\encoderWaveForm.jpg"; DestDir: "{app}\img\dcMotors"; Flags: ignoreversion
Source: "iCubProductionTestSuite\img\dcMotors\label1.jpg"; DestDir: "{app}\img\dcMotors"; Flags: ignoreversion
Source: "iCubProductionTestSuite\img\dcMotors\label2.jpg"; DestDir: "{app}\img\dcMotors"; Flags: ignoreversion
Source: "iCubProductionTestSuite\img\dcMotors\noEncoder.jpg"; DestDir: "{app}\img\dcMotors"; Flags: ignoreversion
Source: "iCubProductionTestSuite\img\dcMotors\probes.jpg"; DestDir: "{app}\img\dcMotors"; Flags: ignoreversion
Source: "iCubProductionTestSuite\img\dcMotors\pws.jpg"; DestDir: "{app}\img\dcMotors"; Flags: ignoreversion
Source: "iCubProductionTestSuite\img\dcMotors\setup.jpg"; DestDir: "{app}\img\dcMotors"; Flags: ignoreversion
Source: "iCubProductionTestSuite\img\dcMotors\yesEncoder.jpg"; DestDir: "{app}\img\dcMotors"; Flags: ignoreversion
Source: "iCubProductionTestSuite\img\mc4plus\can-connect.jpg"; DestDir: "{app}\img\mc4plus"; Flags: ignoreversion
Source: "iCubProductionTestSuite\img\mc4plus\check-leds.gif"; DestDir: "{app}\img\mc4plus"; Flags: ignoreversion
Source: "iCubProductionTestSuite\img\mc4plus\connections1.jpg"; DestDir: "{app}\img\mc4plus"; Flags: ignoreversion
Source: "iCubProductionTestSuite\img\mc4plus\connections2.jpg"; DestDir: "{app}\img\mc4plus"; Flags: ignoreversion
Source: "iCubProductionTestSuite\img\mc4plus\encoder-u1.gif"; DestDir: "{app}\img\mc4plus"; Flags: ignoreversion
Source: "iCubProductionTestSuite\img\mc4plus\encoder-u2.gif"; DestDir: "{app}\img\mc4plus"; Flags: ignoreversion
Source: "iCubProductionTestSuite\img\mc4plus\encoder-u3.gif"; DestDir: "{app}\img\mc4plus"; Flags: ignoreversion
Source: "iCubProductionTestSuite\img\mc4plus\encoder-u4.gif"; DestDir: "{app}\img\mc4plus"; Flags: ignoreversion
Source: "iCubProductionTestSuite\img\mc4plus\eth-1.jpg"; DestDir: "{app}\img\mc4plus"; Flags: ignoreversion
Source: "iCubProductionTestSuite\img\mc4plus\eth-2.jpg"; DestDir: "{app}\img\mc4plus"; Flags: ignoreversion
Source: "iCubProductionTestSuite\img\mc4plus\fault-1.jpg"; DestDir: "{app}\img\mc4plus"; Flags: ignoreversion
Source: "iCubProductionTestSuite\img\mc4plus\fault-2.jpg"; DestDir: "{app}\img\mc4plus"; Flags: ignoreversion
Source: "iCubProductionTestSuite\img\mc4plus\flashapp.jpg"; DestDir: "{app}\img\mc4plus"; Flags: ignoreversion
Source: "iCubProductionTestSuite\img\mc4plus\fw-running.gif"; DestDir: "{app}\img\mc4plus"; Flags: ignoreversion
Source: "iCubProductionTestSuite\img\mc4plus\setup.jpg"; DestDir: "{app}\img\mc4plus"; Flags: ignoreversion

Source: "iCubProductionTestSuite\img\mc4plus-cshape\mc4plus-cshape.jpg"; DestDir: "{app}\img\mc4plus-cshape"; Flags: ignoreversion
Source: "iCubProductionTestSuite\img\mc4plus-cshape\mc4plus-cshape-app-run.gif"; DestDir: "{app}\img\mc4plus-cshape"; Flags: ignoreversion
Source: "iCubProductionTestSuite\img\mc4plus-cshape\mc4plus-cshape-setup.jpg"; DestDir: "{app}\img\mc4plus-cshape"; Flags: ignoreversion
Source: "iCubProductionTestSuite\img\mc4plus-cshape\mc4plus-cshape-test-led.gif"; DestDir: "{app}\img\mc4plus-cshape"; Flags: ignoreversion
Source: "iCubProductionTestSuite\img\mc4plus-cshape\eth-2.jpg"; DestDir: "{app}\img\mc4plus-cshape"; Flags: ignoreversion



Source: "iCubProductionTestSuite\img\mtb4\MTB4.jpg"; DestDir: "{app}\img\mtb4"; Flags: ignoreversion
Source: "iCubProductionTestSuite\img\mtb4\MTB4_can.jpg"; DestDir: "{app}\img\mtb4"; Flags: ignoreversion
Source: "iCubProductionTestSuite\img\mtb4\MTB4_gpio.jpg"; DestDir: "{app}\img\mtb4"; Flags: ignoreversion
Source: "iCubProductionTestSuite\img\mtb4\MTB4_ledoff.jpg"; DestDir: "{app}\img\mtb4"; Flags: ignoreversion
Source: "iCubProductionTestSuite\img\mtb4\MTB4_ledon.jpg"; DestDir: "{app}\img\mtb4"; Flags: ignoreversion
Source: "iCubProductionTestSuite\img\mtb4\MTB4_setup.jpg"; DestDir: "{app}\img\mtb4"; Flags: ignoreversion
Source: "iCubProductionTestSuite\img\mtb4\MTB4_short.jpg"; DestDir: "{app}\img\mtb4"; Flags: ignoreversion
Source: "iCubProductionTestSuite\img\strain2\strain2_ledOFF.jpg"; DestDir: "{app}\img\strain2"; Flags: ignoreversion
Source: "iCubProductionTestSuite\img\strain2\strain2_ledON.jpg"; DestDir: "{app}\img\strain2"; Flags: ignoreversion
Source: "iCubProductionTestSuite\img\strain2\strain2_setup1.jpg"; DestDir: "{app}\img\strain2"; Flags: ignoreversion
Source: "iCubProductionTestSuite\img\strain2\strain2_setup2.jpg"; DestDir: "{app}\img\strain2"; Flags: ignoreversion
Source: "iCubProductionTestSuite\img\strain2\strain2_short.jpg"; DestDir: "{app}\img\strain2"; Flags: ignoreversion
Source: "iCubProductionTestSuite\ipts.xml"; DestDir: "{app}"; Flags: ignoreversion
Source: "iCubProductionTestSuite\settings.xml"; DestDir: "{app}"; Flags: ignoreversion
Source: "iCubProductionTestSuite\bin\Release\iCubProductionTestSuite.exe"; DestDir: "{app}\bin\Release"; Flags: ignoreversion
Source: "iCubProductionTestSuite\bin\Release\iCubProductionTestSuite.exe.config"; DestDir: "{app}\bin\Release"; Flags: ignoreversion
Source: "iCubProductionTestSuite\bin\Release\iCubProductionTestSuite.pdb"; DestDir: "{app}\bin\Release"; Flags: ignoreversion
Source: "iCubProductionTestSuite\bin\Release\NtcanNet.dll"; DestDir: "{app}\bin\Release"; Flags: ignoreversion
Source: "iCubProductionTestSuite\bin\Release\NtcanNet.xml"; DestDir: "{app}\bin\Release"; Flags: ignoreversion
Source: "iCubProductionTestSuite\tools\boards\icub-firmware-build\setup-fw-repo.bat"; DestDir: "{app}\tools\boards\icub-firmware-build"; Flags: ignoreversion
Source: "iCubProductionTestSuite\tools\boards\icub-firmware-build\udpdate-fw-repo.bat"; DestDir: "{app}\tools\boards\icub-firmware-build"; Flags: ignoreversion
Source: "iCubProductionTestSuite\tools\boards\mc4plus\eth\test_eth.bat"; DestDir: "{app}\tools\boards\mc4plus\eth"; Flags: ignoreversion
Source: "iCubProductionTestSuite\tools\boards\mc4plus\flash\mc4plus_prod.bat"; DestDir: "{app}\tools\boards\mc4plus\flash"; Flags: ignoreversion
Source: "iCubProductionTestSuite\tools\boards\mc4plus\flash\mc4plus_reset.bat"; DestDir: "{app}\tools\boards\mc4plus\flash"; Flags: ignoreversion
Source: "iCubProductionTestSuite\tools\boards\mc4plus\flash\mc4plus_test.bat"; DestDir: "{app}\tools\boards\mc4plus\flash"; Flags: ignoreversion
Source: "iCubProductionTestSuite\tools\boards\mc4plus\flash\hex\mc4plus_test.hex"; DestDir: "{app}\tools\boards\mc4plus\flash\hex"; Flags: ignoreversion
Source: "iCubProductionTestSuite\tools\boards\mtb4\flash\mtb4_prod.bat"; DestDir: "{app}\tools\boards\mtb4\flash"; Flags: ignoreversion
Source: "iCubProductionTestSuite\tools\boards\mtb4\flash\mtb4_test.bat"; DestDir: "{app}\tools\boards\mtb4\flash"; Flags: ignoreversion
Source: "iCubProductionTestSuite\tools\boards\mtb4\flash\hex\mtb4_test.hex"; DestDir: "{app}\tools\boards\mtb4\flash\hex"; Flags: ignoreversion
Source: "iCubProductionTestSuite\tools\boards\strain2\flash\strain2_prod.bat"; DestDir: "{app}\tools\boards\strain2\flash"; Flags: ignoreversion
Source: "iCubProductionTestSuite\tools\boards\strain2\flash\strain2_reset.bat"; DestDir: "{app}\tools\boards\strain2\flash"; Flags: ignoreversion
Source: "iCubProductionTestSuite\tools\boards\strain2\flash\strain2_test.bat"; DestDir: "{app}\tools\boards\strain2\flash"; Flags: ignoreversion
Source: "iCubProductionTestSuite\tools\boards\strain2\flash\hex\strain2_test.hex"; DestDir: "{app}\tools\boards\strain2\flash\hex"; Flags: ignoreversion
Source: "iCubProductionTestSuite\tools\Git-2.31.1-64-bit.exe"; DestDir: "{app}\tools"; Flags: ignoreversion
Source: "iCubProductionTestSuite\tools\boards\mtb4\flash\mtb4c_prod.bat"; DestDir: "{app}\tools\boards\mtb4\flash"; Flags: ignoreversion
Source: "iCubProductionTestSuite\tools\boards\mtb4\flash\mtb4c_test.bat"; DestDir: "{app}\tools\boards\mtb4\flash"; Flags: ignoreversion
Source: "iCubProductionTestSuite\tools\boards\mtb4\flash\hex\mtb4_revB_test_v190.hex"; DestDir: "{app}\tools\boards\mtb4\flash\hex"; Flags: ignoreversion
Source: "iCubProductionTestSuite\tools\boards\mtb4\flash\hex\mtb4_revC_test_v190.hex"; DestDir: "{app}\tools\boards\mtb4\flash\hex"; Flags: ignoreversion
Source: "iCubProductionTestSuite\tools\boards\strain2\flash\hex\strain2_revB_test_v190.hex"; DestDir: "{app}\tools\boards\strain2\flash\hex"; Flags: ignoreversion
Source: "iCubProductionTestSuite\tools\boards\strain2\flash\hex\strain2_revC_test_v1B0.hex"; DestDir: "{app}\tools\boards\strain2\flash\hex"; Flags: ignoreversion
Source: "iCubProductionTestSuite\tools\boards\strain2\flash\strain2c_prod.bat"; DestDir: "{app}\tools\boards\strain2\flash"; Flags: ignoreversion
Source: "iCubProductionTestSuite\tools\boards\strain2\flash\strain2c_test.bat"; DestDir: "{app}\tools\boards\strain2\flash"; Flags: ignoreversion
Source: "iCubProductionTestSuite\img\rfe\rfe-bottom.png"; DestDir: "{app}\img\rfe"; Flags: ignoreversion
Source: "iCubProductionTestSuite\img\rfe\rfe-j1.jpg"; DestDir: "{app}\img\rfe"; Flags: ignoreversion
Source: "iCubProductionTestSuite\img\rfe\rfe-j2.jpg"; DestDir: "{app}\img\rfe"; Flags: ignoreversion
Source: "iCubProductionTestSuite\img\rfe\rfe-j5.jpg"; DestDir: "{app}\img\rfe"; Flags: ignoreversion
Source: "iCubProductionTestSuite\img\rfe\rfe-j5_2.jpg"; DestDir: "{app}\img\rfe"; Flags: ignoreversion
Source: "iCubProductionTestSuite\img\rfe\rfe-j10.jpg"; DestDir: "{app}\img\rfe"; Flags: ignoreversion
Source: "iCubProductionTestSuite\img\rfe\rfe-j11.jpg"; DestDir: "{app}\img\rfe"; Flags: ignoreversion
Source: "iCubProductionTestSuite\img\rfe\rfe-j12.jpg"; DestDir: "{app}\img\rfe"; Flags: ignoreversion
Source: "iCubProductionTestSuite\img\rfe\rfe-j13.jpg"; DestDir: "{app}\img\rfe"; Flags: ignoreversion
Source: "iCubProductionTestSuite\img\rfe\rfe-ledOFF.jpg"; DestDir: "{app}\img\rfe"; Flags: ignoreversion
Source: "iCubProductionTestSuite\img\rfe\rfe-ledON.jpg"; DestDir: "{app}\img\rfe"; Flags: ignoreversion
Source: "iCubProductionTestSuite\img\rfe\rfe-setup.jpg"; DestDir: "{app}\img\rfe"; Flags: ignoreversion
Source: "iCubProductionTestSuite\img\rfe\rfe-top.png"; DestDir: "{app}\img\rfe"; Flags: ignoreversion
Source: "iCubProductionTestSuite\tools\boards\rfe\flash\hex\rfe.test.v183.hex"; DestDir: "{app}\tools\boards\rfe\flash\hex"; Flags: ignoreversion
Source: "iCubProductionTestSuite\tools\boards\rfe\flash\rfe_prod.bat"; DestDir: "{app}\tools\boards\rfe\flash"; Flags: ignoreversion
Source: "iCubProductionTestSuite\tools\boards\rfe\flash\rfe_reset.bat"; DestDir: "{app}\tools\boards\rfe\flash"; Flags: ignoreversion
Source: "iCubProductionTestSuite\tools\boards\rfe\flash\rfe_test.bat"; DestDir: "{app}\tools\boards\rfe\flash"; Flags: ignoreversion
Source: "iCubProductionTestSuite\img\fap5\fap5-setup.jpg"; DestDir: "{app}\img\fap5"; Flags: ignoreversion
Source: "iCubProductionTestSuite\img\amc-bldc\amc-bldc_encoders.gif"; DestDir: "{app}\img\amc-bldc"; Flags: ignoreversion
Source: "iCubProductionTestSuite\img\amc-bldc\amc-bldc_FAULT_OFF.jpg"; DestDir: "{app}\img\amc-bldc"; Flags: ignoreversion
Source: "iCubProductionTestSuite\img\amc-bldc\amc-bldc_FAULT_ON.jpg"; DestDir: "{app}\img\amc-bldc"; Flags: ignoreversion
Source: "iCubProductionTestSuite\img\amc-bldc\amc-bldc_LED_OFF.jpg"; DestDir: "{app}\img\amc-bldc"; Flags: ignoreversion
Source: "iCubProductionTestSuite\img\amc-bldc\amc-bldc_LED_ON.jpg"; DestDir: "{app}\img\amc-bldc"; Flags: ignoreversion
Source: "iCubProductionTestSuite\img\amc-bldc\amc-bldc_setup.jpg"; DestDir: "{app}\img\amc-bldc"; Flags: ignoreversion
Source: "iCubProductionTestSuite\tools\boards\amc-bldc\flash\amc-bldc_prod.bat"; DestDir: "{app}\tools\boards\amc-bldc\flash"; Flags: ignoreversion
Source: "iCubProductionTestSuite\tools\boards\amc-bldc\flash\amc-bldc_test.bat"; DestDir: "{app}\tools\boards\amc-bldc\flash"; Flags: ignoreversion
Source: "iCubProductionTestSuite\tools\boards\amc-bldc\flash\hex\amcbldc.test.hex"; DestDir: "{app}\tools\boards\amc-bldc\flash\hex"; Flags: ignoreversion

[UninstallDelete]
Type: filesandordirs; Name: "{app}\tools"
Type: filesandordirs; Name: "{app}\img"
Type: filesandordirs; Name: "{app}\bin"
Type: filesandordirs; Name: "{app}\TestReports"
Type: files; Name: "{app}\*.*"
